# Generated by Django 2.1.1 on 2018-09-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My List', max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('static_id', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
