# Generated by Django 2.1.1 on 2018-09-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listobject',
            name='name',
            field=models.CharField(blank=True, default='My List', max_length=255),
        ),
    ]
