# Generated by Django 2.1.1 on 2018-09-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listobject',
            name='id',
        ),
        migrations.AlterField(
            model_name='listobject',
            name='static_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
