# Generated by Django 2.1.1 on 2018-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181027_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listobject',
            name='readOnly',
            field=models.BooleanField(default=False),
        ),
    ]
