# Generated by Django 2.1.1 on 2018-10-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181027_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_guests',
            field=models.IntegerField(default=0),
        ),
    ]
