# Generated by Django 2.1.1 on 2018-09-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180903_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_users',
            field=models.TextField(blank=True),
        ),
    ]
