# Generated by Django 2.1.1 on 2018-09-21 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_item_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listobject',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='listobject',
            name='collaborators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
