# Generated by Django 2.1.1 on 2019-01-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOff',
            fields=[
                ('name', models.CharField(default='New List', max_length=255)),
                ('static_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
