# Generated by Django 2.1.1 on 2019-02-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190113_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneoff',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 2, 9, 16, 53, 57, 395195)),
            preserve_default=False,
        ),
    ]
