# Generated by Django 2.1.1 on 2019-02-09 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_oneoff_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneoff',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
