# Generated by Django 2.1.1 on 2019-02-23 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190209_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
