# Generated by Django 2.1.1 on 2019-03-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_item_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='listobject',
            name='background_image_download_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listobject',
            name='background_image_owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listobject',
            name='background_image_owner_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listobject',
            name='background_image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
